controllers/main.py
import os
import sys
from flask import jsonify,render_template,send_file, request,flash, redirect ,url_for,session,send_file, Blueprint,request
import time
import datetime
import json
import boto3
from collections import defaultdict
from helpers.sib_meta import *
from helpers.meta_create import *
from helpers.meta_extract import *
from helpers.forms import *
from jinja2.exceptions import TemplateNotFound

boto3.setup_default_session(profile_name='sib')
dynamodb = boto3.resource('dynamodb')
meta_table = dynamodb.Table('sibylity_fcr_metadata')

index = Blueprint('index', __name__)

@index.route('/',methods=['GET','POST'])
def dashboard():
    try:
        metadata = get_metadata(meta_table)
        return render_template(
            'list.html',
            metadata = metadata,
            list_title="Metadata",
            active_page="dashboard"
        )
    except TemplateNotFound:
        abort(404)
    return 


@index.route('/settings',methods=['GET','POST'])
def settings():
    try:
        metadata = get_settings_metadata(meta_table)
        return render_template(
            'settings/list.html',
            metadata = metadata,
            list_title="Settings",
            active_page="settings",
        )
    except TemplateNotFound:
        abort(404)
    return 


@index.route('/threats',methods=['GET','POST'])
def threats():
    try:
        metadata = get_threats_metadata(meta_table)
        return render_template(
            'threats/list.html',
            metadata = metadata,
            list_title="Threats",
            active_page="threats",
        )
    except TemplateNotFound:
        abort(404)
    return


@index.route('/scope',methods=['GET','POST'])
def project_scope_settings():
    try:
        metadata = get_project_scope_settings_metadata(meta_table)
        return render_template(
            'list.html',
            metadata = metadata,
            list_title="Project Scope Settings",
            active_page="scope",
        )
    except TemplateNotFound:
        abort(404)
    return


@index.route('/control-families',methods=['GET','POST'])
def control_families():
    try:
        metadata = get_control_families_metadata(meta_table)
        return render_template(
            'control_families/list.html',
            metadata = metadata,
            list_title="Control Families",
            active_page="families",
        )
    except TemplateNotFound:
        abort(404)
    return


@index.route('/controls',methods=['GET','POST'])
def controls():
    try:
        vulnerabilities = get_vulnerabilities_metadata(meta_table)
        controls = get_controls_metadata(meta_table)
        vulnerabilities = sorted(vulnerabilities, key=lambda d: d['id'])
        controls = sorted(controls, key=lambda d: d['id'])
        
        return render_template(
            'controls/list.html',
            controls = controls,
            vulnerabilities = vulnerabilities,
            list_title="Vulnerabilities and Controls",
            active_page="controls",
        )
    except TemplateNotFound:
        abort(404)
    return


@index.route('/valuesets',methods=['GET','POST'])
def valuesets():
    try:
        metadata = get_valuesets_metadata(meta_table)
        return render_template(
            'valuesets/list.html',
            metadata = metadata,
            list_title="Valuesets",
            active_page="valuesets",
        )
    except TemplateNotFound:
        abort(404)
    return


@index.route('/create-control',methods=['GET','POST'])
def create_control():

    try:
        metadata = get_metadata(meta_table)
        control_families = [x['key'] for x in  metadata if x['class']== "control_family"]
        threats = [x['key'] for x in  metadata if x['class'] == "threat"]
                

        if request.method == 'POST':
            form = request.form
            control = extract_control(form)
            vulnerability = extract_vulnerability(form,threats)
            success1 = ddb_create_control(meta_table,control)
            if success1:
                success2 = ddb_create_vulnerability(meta_table,vulnerability)
            if success1 and success2:
                return redirect(url_for('index.controls'))
            
        return render_template(
            'controls/create.html',
            control_families = control_families,
            threats = threats
        )
    except TemplateNotFound:
        abort(404)
    return


@index.route('/create-settings',methods=['GET','POST'])
def create_settings():
    try:
        if request.method == 'POST':
            form = request.form
            settings = extract_settings(form)
            success = ddb_create(meta_table,settings)
            print(success)
            if success:
                return redirect(url_for('index.settings'))
            
        return render_template(
            'settings/create.html',
        )
    except TemplateNotFound:
        abort(404)
    return


@index.route('/create-threat',methods=['GET','POST'])
def create_threat():
    try:
        if request.method == 'POST':
            form = request.form
            threat = extract_threat(form)
            success = ddb_create_threat(meta_table,threat)
            print(success)
            if success:
                return redirect(url_for('index.threats'))
            
        return render_template(
            'threats/create.html',
        )
    except TemplateNotFound:
        abort(404)
    return


@index.route('/create-control-family',methods=['GET','POST'])
def create_control_family():
    try:
        if request.method == 'POST':
            form = request.form
            cf = extract_control_family(form)
            success = ddb_create_control_family(meta_table,cf)
            print(success)
            if success:
                return redirect(url_for('index.control_families'))
            
        return render_template(
            'control_families/create.html',
        )
    except TemplateNotFound:
        abort(404)
    return


@index.route('/create-valueset',methods=['GET','POST'])
def create_valueset():
    try:
        if request.method == 'POST':
            form = request.form
            vs = extract_valueset(form)
            success = ddb_create_control_family(meta_table,vs)
            if success:
                return redirect(url_for('index.valuesets'))
            print(success)
            
        return render_template(
            'valuesets/create.html',
        )
    except TemplateNotFound:
        abort(404)
    return

templates/includes/css_imports.html
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Siblity Curator</title>
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<link href="{{url_for('static', filename = 'assets/img/apple-icon.png')}}" rel="apple-touch-icon" sizes="76x76">
<link href="{{url_for('static', filename = 'assets/img/favicon.ico')}}" rel="icon" type="image/x-icon">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
<link href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.css" rel="stylesheet" type="text/css">
<link href="https://unpkg.com/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />
<link href="{{url_for('static', filename = 'assets/css/nucleo-icons.css')}}" rel="stylesheet" />
<link href="{{url_for('static', filename = 'assets/css/nucleo-svg.css')}}" rel="stylesheet" />
<link href="{{url_for('static', filename = 'assets/css/material-dashboard.css')}}?v=3.0.0" id="pagestyle"  rel="stylesheet" />
<link href="{{url_for('static', filename = 'assets/plugins/jsoneditor/jsoneditor.css')}}?v=3.0.0" id="pagestyle" rel="stylesheet" />
<link href="{{ url_for('static', filename = 'assets/plugins/chosen/css/chosen.css') }}" rel="stylesheet" >
<link href="{{ url_for('static', filename = 'assets/plugins/chosen/css/prism.css') }}" rel="stylesheet" >
<link href="{{ url_for('static', filename = 'assets/plugins/jsonforms/opt/bootstrap.css') }}" rel="stylesheet" >
<link href="{{ url_for('static', filename = 'assets/plugins/jsonforms/opt/bootstrap-wysihtml5.css') }}" rel="stylesheet" >
<link href="{{ url_for('static', filename = 'assets/plugins/jsonforms/opt/spectrum.css')}}" rel="stylesheet" >
<link href="{{url_for('static', filename = 'assets/css/custom.css')}}" id="pagestyle"  rel="stylesheet" />

templates/includes/footer.html
<footer class="footer py-4  ">
    <div class="container-fluid">
      <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-6 mb-lg-0 mb-4">
          <div class="copyright text-center text-sm text-muted text-lg-start">
            © <script>
              document.write(new Date().getFullYear())
            </script>,
            made with <i class="fa fa-heart"></i> by
            <a href="#" class="font-weight-bold" target="_blank">SibylSoft</a>
            for internal use.
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/js_imports.html
  <script src="{{url_for('static', filename = 'assets/js/core/popper.min.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/js/core/bootstrap.min.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/js/plugins/perfect-scrollbar.min.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/js/plugins/smooth-scrollbar.min.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsoneditor/jsoneditor.js')}}"></script>
  <script src="https://buttons.github.io/buttons.js" async defer></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="{{url_for('static', filename = 'assets/js/material-dashboard.min.js')}}?v=3.0.0"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js" type="text/javascript" charset="utf8" ></script>
  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript" charset="utf8" ></script>
  <script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js" type="text/javascript" charset="utf8" ></script>
  <script src="https://cdn.datatables.net/select/1.2.5/js/dataTables.select.min.js" type="text/javascript" charset="utf8" ></script>
  <script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js" type="text/javascript" charset="utf8" ></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/underscore.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/jsv.js')}}"></script>
  {# <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/jquery-ui.js')}}"></script> #}
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/bootstrap-dropdown.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/bootstrap-wysihtml5.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/spectrum.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/ace/ace.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/ace/mode-json.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/ace/mode-html.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/ace/mode-css.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/ace/mode-javascript.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/ace/mode-less.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/ace/mode-markdown.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/opt/jquery.transloadit2.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/jsonforms/jsonform.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/js/jquery.json-editor.min.js')}}"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/chosen/js/chosen.jquery.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/chosen/js/prism.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename = 'assets/plugins/chosen/js/init.js')}}" type="text/javascript"></script>
  <script src="https://unpkg.com/@yaireo/tagify"></script>
  <script src="https://unpkg.com/@yaireo/tagify/dist/tagify.polyfills.min.js"></script>

templates/includes/sidenav.html
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href="{{ url_for('index.dashboard') }}" target="_blank">
        <img src="https://irp.cdn-website.com/8c67ee4c/dms3rep/multi/logo-SibylSoft+%285%29.svg" class="navbar-brand-img h-100" alt="main_logo">
      </a>
    </div>
    <div class="collapse navbar-collapse h-auto w-auto  max-height-vh-100" id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white {{ 'active' if active_page == 'dashboard' else '' }} bg-gradient-primary" href="{{ url_for('index.dashboard') }}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white {{ 'active' if active_page == 'settings' else '' }} bg-gradient-primary" href="{{ url_for('index.settings') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">dashboard</i>
              </div>
              <span class="nav-link-text ms-1">Settings</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white {{ 'active' if active_page == 'threats' else '' }} bg-gradient-primary" href="{{ url_for('index.threats') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">dashboard</i>
              </div>
              <span class="nav-link-text ms-1">Threats</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white {{ 'active' if active_page == 'controls' else '' }} bg-gradient-primary" href="{{ url_for('index.controls') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">dashboard</i>
              </div>
              <span class="nav-link-text ms-1">Controls</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white {{ 'active' if active_page == 'families' else '' }} bg-gradient-primary" href="{{ url_for('index.control_families') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">dashboard</i>
              </div>
              <span class="nav-link-text ms-1">Control Families</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white {{ 'active' if active_page == 'valuesets' else '' }} bg-gradient-primary" href="{{ url_for('index.valuesets') }}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">dashboard</i>
              </div>
              <span class="nav-link-text ms-1">Valuesets</span>
            </a>
          </li>
      </ul>
    </div>
</aside>

templates/includes/topnav.html
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
    <div class="container-fluid py-1 px-3">
      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
        <ul class="navbar-nav  justify-content-end">
          <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
              <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
              </div>
            </a>
          </li>
        </ul>
      </div>
    </div>
</nav>